# Generated by Django 4.2.10 on 2024-03-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domo_api', '0003_devices_dots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='loction',
            new_name='location',
        ),
    ]
