# Generated by Django 4.2.10 on 2024-03-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domo_api', '0004_rename_loction_devices_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dots',
            old_name='datTime',
            new_name='dateTime',
        ),
    ]
